# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inverse_arma <- function(m) {
    .Call('_fastgpbart_inverse_arma', PACKAGE = 'fastgpbart', m)
}

initialize_test <- function(x_train, x_test, residuals, phi, nu, tau, tau_mu, node_min_size) {
    .Call('_fastgpbart_initialize_test', PACKAGE = 'fastgpbart', x_train, x_test, residuals, phi, nu, tau, tau_mu, node_min_size)
}

dhcauchy <- function(x, location, sigma) {
    .Call('_fastgpbart_dhcauchy', PACKAGE = 'fastgpbart', x, location, sigma)
}

bart <- function(x_train, y, x_test, n_tree, n_mcmc, n_burn, n_min_size, tau, mu, tau_mu, naive_sigma, alpha, beta) {
    .Call('_fastgpbart_bart', PACKAGE = 'fastgpbart', x_train, y, x_test, n_tree, n_mcmc, n_burn, n_min_size, tau, mu, tau_mu, naive_sigma, alpha, beta)
}

omega <- function(x_train, phi, nu) {
    .Call('_fastgpbart_omega', PACKAGE = 'fastgpbart', x_train, phi, nu)
}

omega_plus_tau <- function(x_train, phi, nu, tau) {
    .Call('_fastgpbart_omega_plus_tau', PACKAGE = 'fastgpbart', x_train, phi, nu, tau)
}

distance_matrix <- function(x_train, x_test) {
    .Call('_fastgpbart_distance_matrix', PACKAGE = 'fastgpbart', x_train, x_test)
}

